### ISSUE TITLE
mysql start error

### ISSUE THREAD

**Issue by zevingao** [ZpGuo/zPhal-dockerfiles#1]
hello my boy, I got this problem
mysql-db_1_77e5eef18e48 | mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 - Permission denied)
mysql-db_1_77e5eef18e48 | mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
咋整的老哥，docker-compose.yml里面配置privileged：true也不行呀。求助，谢谢！

**Comment by goozp** [comment]
这个报错挺明显了呀，权限控制处理一下
